CREATE TABLE all_users (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(25) UNIQUE NOT NULL,
    `email` VARCHAR(40) NOT NULL,
    `password` VARCHAR(20) NOT NULL
);

CREATE TABLE skills (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `skill` VARCHAR(200) NOT NULL
);